### ISSUE TITLE
C# mapping is not required

### ISSUE THREAD

**Issue by alexeyzimarev** [gaearon/gitbook-plugin-prism#14]
Currently the `csharp` is mapped to `cs` and the plugin tries to load `prismjs/components/prism-cs.js`. However, prism.js has it as `prismjs/components/prism-csharp.js`.

Suggestion is to revert the mapping (cs->csharp) or remove the mapping.

**Comment by robmcguinness** [comment]
I think your suggestions are reasonable and would be considered a **fix**  but I wonder why the mapping from `csharp` **=>** `cs` was created to begin with?   Maybe this has always been a bug but I'm not sure.  

Let me do some quick investigation first before fixing the mapping.

**Comment by alexeyzimarev** [comment]
I know that `cs` is the valid shortcut for `csharp` so I assume the mapping was intended to be there but got reversed and never worked.

**Comment by robmcguinness** [comment]
That is what i'm concluding as well.  I'll submit a fix by reversing the mapping.

**Comment by robmcguinness** [comment]
@alexeyzimarev I published the fix to NPM.  Please try now.

**Comment by alexeyzimarev** [comment]
Yeah, thanks, it works fine 👍
