### ISSUE TITLE
Ignore certain languages from being parsed by Prism

### ISSUE THREAD

**Issue by howlowck** [gaearon/gitbook-plugin-prism#28]
There are certain gitbook plugins that uses the three back-ticks to denote the code to be rendered.
See [mermaid-full usage](https://github.com/yanni4night/gitbook-plugin-mermaid-full/issues/3)
And prism gives a warning like:
```
Failed to load prism syntax: graph
{ Error: Cannot find module 'prismjs/components/prism-graph.js' ...
```

It would be nice to have an option to ignore certain "languages" from being parsed by prism.

**Comment by robmcguinness** [comment]
I think this is reasonable. Little busy right now but maybe I can make updates to the framework early next week this this feature.

**Comment by howlowck** [comment]
I made the changes. Let me know if there is anything else needed to improved the PR.  Thanks!

**Comment by JoeyBling** [comment]
Hi, how did you solve it?
