### ISSUE TITLE
What is the gitbook default theme

### ISSUE THREAD

**Issue by calebeaires** [gaearon/gitbook-plugin-prism#33]
gitbook default theme is clean and beautifull. I was wondering, which is the gitbook default theme?

<img width="755" alt="screen shot 2018-11-09 at 17 24 23" src="https://user-images.githubusercontent.com/794195/48283677-5634a580-e444-11e8-999b-fd287ef483e3.png">

**Comment by robmcguinness** [comment]
This plugin uses https://github.com/gaearon/gitbook-plugin-prism#L57 that defaults to https://github.com/PrismJS/prism/blob/master/themes/prism.css. 

You can override the prim themes using https://github.com/gaearon/gitbook-plugin-prism#css. Please reopen if i didn't answer the question clearly.

**Comment by calebeaires** [comment]
Actually, I refered to the "theme name", so I will install it on VSCode
