### ISSUE TITLE
Theme change does not work

### ISSUE THREAD

**Issue by pitrew** [gaearon/gitbook-plugin-prism#9]
When I try to use different theme in book.json the output is broken.

**Comment by robmcguinness** [comment]
@pitrew can you give a bit more detail about what is broken?

**Comment by pitrew** [comment]
Sure, so I followed instructions to enable this plugin from README.md. Then instead of using default theme I've changed it to dark:

```
"pluginsConfig": {  
  "prism": {
    "css": [
      "prismjs/themes/prism-dark.css"
    ]
  }
}
```

and it does not display correctly. 

Checking DOM I notticed that there is astructure like this:

```
<pre>
  <code class="lang-js">
   Code....
  </code>
</pre>
```

then I eddited those nodes manually to 

```
<pre class="language-javascript">
  <code class="language-javascript">
   Code....
  </code>
</pre>
```

it was working fine.

**Comment by robmcguinness** [comment]
by any chance do you have a sample repo with the issue?  if not I can try and recreate later today.

**Comment by robmcguinness** [comment]
I created a sample repo [gitbook-prism-example](https://github.com/robmcguinness/gitbook-prism-example) and was able to recreate the issue.  I'll investigate further later today.

**Comment by robmcguinness** [comment]
@pitrew Thanks for the heads up.  The color themes were not being applied without the proper classes on the `<pre>` and `<code` blocks.  PR #10 should have a a workaround.

**Comment by pitrew** [comment]
@robmcguinness good stuff, thanks
